### ISSUE TITLE
Incorrect values for /model_car/yaw

### ISSUE THREAD

**Issue by arieleo2690** [AutoModelCar/AutoModelCarWiki#10]
Hi.

I'm trying to read the yaw value through Arduino serial port in /model_car/yaw topic. However I'm getting incorrect values from -180 to 180 since model car is static. I reviewed the source code in heading package, but it seems to me it's only reading the value over Arduino serial port.
Regards.

**Comment by noelcortes** [comment]
Arduino UNO only reads the IMU data from the serial port, so maybe you have a problem with the sparkfun IMU or just a drift error.....  You can read the yaw signal trhough the "serial monitor" of arduino IDE in order to check the correct operation of the sparkfun IMU, just remember to adjust the baud rate to read this measurements properly..

Regards.

Noel Cortés - CINVESTAV Saltillo

**Comment by ZahraBoroujeni** [comment]
Hi , 
@arieleo2690 : Do you use version 2? Could you turn off the lidar and test again?! 

- After 10 seconds the IMU yaw angle should reach a number. 

Then if it is stable without lidar.

- Turn on the lidar and use the IMU_Zero code to calibrate the IMU again. You should update the lines below in main code, and test it again.

- [x] - mpu.setXAccelOffset(-1643); 
- [x] - mpu.setYAccelOffset(589);
- [x] - mpu.setZAccelOffset(1333);
- [x] - mpu.setXGyroOffset(418);
- [x] - mpu.setYGyroOffset(-57);
- [x] - mpu.setZGyroOffset(69);

IMU_Zero code: https://github.com/AutoModelCar/arduino_nano_v2/tree/master/MPU6050/examples/IMU_Zero 

@noelcortes : In arduino main code, using MPU6050 library, the yaw angle is calculated and then it sends through serial port.
Best,
Zahra

**Comment by arieleo2690** [comment]
It works. Thanks Zahra.
